# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '17 1 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天09点
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！

permissions:
  contents: read

jobs:
  sign-in:
    runs-on: ubuntu-22.04
    steps:
        # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and publish
      env:
         USERNAME: ${{ secrets.USERNAME }}
         PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python checkin.py
